spring.application.name=neatnest_Webtechnologies_Projekt

# ??? Server ???????????????????????????????????????

#Serverport
server.port=8080


# DB Konfigurationsdatei
spring.datasource.url=jdbc:h2:file:./data/neatnest
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=admin
spring.datasource.password=initinit
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Tabellen automatisch erstellen/updaten
spring.jpa.hibernate.ddl-auto=update

# H2 Browser-Konsole (zum Debuggen)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Session-Security :D (siehe doku)
server.servlet.session.cookie.http-only=true
server.servlet.session.cookie.same-site=strict

# Debuglogging
logging.level.org.springframework.security=DEBUG